import Image from 'next/image';import {Container} from '@/components/ui/Container';import {SectionEyebrow} from '@/components/ui/SectionEyebrow';import {Button} from '@/components/ui/Button';import {practiceAreas} from '@/data/practice-areas';import {professionals} from '@/data/professionals';import {articles} from '@/data/articles';import {faq} from '@/data/faq';import {siteConfig,fullAddress} from '@/config/site';import {whatsappUrl} from '@/lib/whatsapp';import {googleMapsEmbedUrl,googleMapsUrl} from '@/lib/maps';
const board='/images/institutional/meeting-room.png';
export function About(){return <><section className="section" id="escritorio"><Container><div className="split"><div><SectionEyebrow>O ESCRITÓRIO</SectionEyebrow><h2>Conhecimento jurídico aliado a uma atuação próxima e responsável.</h2></div><p>O escritório Brandão, Santos &amp; Folli Advogados Associados atua com foco em atendimento próximo, análise cuidadosa e comunicação clara. Cada situação é compreendida de forma individual, permitindo que as alternativas jurídicas sejam avaliadas com responsabilidade e transparência.<br/><br/>Nosso trabalho busca oferecer acompanhamento jurídico consistente.</p></div><div className="principles">{[['01','Atendimento personalizado','Cada situação é analisada individualmente.'],['02','Comunicação transparente','Comunicação clara e objetiva em todas as etapas.'],['03','Atuação responsável','Trabalho conduzido com ética e atenção.']].map(x=><div key={x[0]}><em>{x[0]}</em><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></Container></section><div className="wide-img"><Image src={board} alt="Sala de reuniões do escritório" fill quality={95} sizes="100vw"/></div></>}
export function PracticeAreas(){return <section className="section mist" id="atuacao"><Container><SectionEyebrow>ÁREAS DE ATUAÇÃO</SectionEyebrow><div className="intro"><h2>Áreas de atuação</h2><p>Atuação jurídica multidisciplinar em diferentes momentos e necessidades corporativas e patrimoniais.</p></div><div className="cards">{practiceAreas.map(x=><article key={x[0]}><em>{x[0]}</em><small>{x[1]}</small><h3>{x[2]}</h3><p>{x[3]}</p><a href="#contato">Ver detalhes →</a></article>)}</div></Container></section>}
export function Approach(){return <section className="navy"><Container><div className="split"><div><SectionEyebrow>NOSSA FORMA DE ATUAR</SectionEyebrow><h2>Cada situação exige escuta atenta, análise cuidadosa e uma estratégia adequada à sua realidade.</h2><p>Nosso trabalho começa pela compreensão cuidadosa de cada situação. A partir dessa análise, avaliamos os caminhos jurídicos disponíveis e orientamos o cliente com clareza.</p></div><div className="approach-list">{[['01','Atendimento Próximo','Acompanhamento contínuo'],['02','Análise Individualizada','Exame detalhado do contexto'],['03','Atuação Responsável','Transparência e segurança']].map(x=><div key={x[0]}><em>{x[0]} •</em><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></div></Container></section>}
export function Professionals(){return <section className="section" id="profissionais"><Container><div className="intro"><div><SectionEyebrow>PROFISSIONAIS</SectionEyebrow><h2>Nossa equipe</h2></div><p>Atuação jurídica construída com conhecimento técnico, comunicação clara e atenção às particularidades.</p></div><p className="image-note">Imagens ilustrativas utilizadas exclusivamente para apresentação do projeto.</p><div className="people">{professionals.map(p=><article key={p.image}><div className="person-img"><Image src={p.image} alt="Imagem ilustrativa de profissional" fill quality={95} sizes="(max-width:800px) 100vw, 33vw"/></div><h3>{p.role}</h3><small>{p.areas}</small><p>Atuação jurídica construída com conhecimento técnico e atenção.</p><a href="#contato">Conheça o profissional →</a></article>)}</div></Container></section>}
export function ServiceProcess(){return <section className="section mist"><Container><SectionEyebrow>METODOLOGIA</SectionEyebrow><div className="intro"><h2>Como funciona o atendimento</h2><p>Um fluxo transparente e estruturado desde o primeiro contato.</p></div><div className="process">{[['01','Contato inicial'],['02','Análise'],['03','Orientação jurídica']].map(x=><div key={x[0]}><em>{x[0]}</em><h3>{x[1]}</h3><p>Compreensão, avaliação e orientação dos próximos passos possíveis.</p></div>)}</div></Container></section>}
export function Articles(){return <section className="section" id="conteudos"><Container><div className="intro"><div><SectionEyebrow>PUBLICAÇÕES &amp; ANÁLISES</SectionEyebrow><h2>Conteúdos jurídicos</h2></div><a href="#contato">Ver todas as publicações →</a></div><div className="articles">{articles.map(x=><article key={x[2]}><small>{x[0]} <time>{x[1]}</time></small><h3>{x[2]}</h3><p>{x[3]}</p><a href="#contato">Ler conteúdo →</a></article>)}</div></Container></section>}
export function FAQ(){return <section className="section mist"><Container><div className="faq"><div><SectionEyebrow>ESCLARECIMENTOS</SectionEyebrow><h2>Dúvidas frequentes</h2>{faq.map(x=><details key={x[0]}><summary>{x[0]} <b>+</b></summary><p>{x[1]}</p></details>)}</div><div><SectionEyebrow>PRESENÇA INSTITUCIONAL</SectionEyebrow><h2>Onde estamos</h2><p>{fullAddress}</p><p>Telefone: {siteConfig.contact.phone}</p><div className="map"><iframe title="Mapa do escritório" src={googleMapsEmbedUrl} loading="lazy" allowFullScreen/></div><a className="map-link" href={googleMapsUrl} target="_blank" rel="noreferrer">Como chegar →</a></div></div></Container></section>}
export function ContactCTA(){return <section className="contact" id="contato"><Container><div><SectionEyebrow>DIÁLOGO INICIAL</SectionEyebrow><h2>Entre em contato com nossa equipe.</h2><p>Para informações sobre atendimento e disponibilidade, utilize um dos nossos canais.</p></div><div className="contact-actions"><Button href={`tel:${siteConfig.contact.phone.replace(/\D/g,'')}`} className="contact-primary">Entrar em contato</Button><a className="contact-whatsapp" href={whatsappUrl} target="_blank" rel="noreferrer" aria-label="Abrir conversa no WhatsApp"><svg className="whatsapp-icon" aria-hidden="true" viewBox="0 0 24 24" fill="none"><path d="M20.5 3.5A11.8 11.8 0 0 0 12.1 0 11.7 11.7 0 0 0 2 17.6L.4 23.5l6-1.6A11.8 11.8 0 0 0 12 24h.1A11.9 11.9 0 0 0 24 12a11.8 11.8 0 0 0-3.5-8.5ZM12.1 22a9.8 9.8 0 0 1-5-1.4l-.4-.2-3.6 1 1-3.5-.2-.4A9.8 9.8 0 1 1 12.1 22Zm5.4-7.4c-.3-.2-1.8-.9-2.1-1s-.5-.2-.7.2-.8 1-1 1.2-.4.2-.7.1a8 8 0 0 1-2.4-1.5 9 9 0 0 1-1.7-2.1c-.2-.4 0-.6.2-.8l.5-.6.2-.5-.1-.4c-.1-.2-.7-1.7-1-2.3-.2-.6-.5-.5-.7-.5h-.6c-.2 0-.5.1-.8.4-.3.3-1 1-1 2.5s1.1 2.9 1.3 3.1c.2.2 2.2 3.4 5.4 4.8.8.3 1.4.5 1.9.6.8.1 1.5.1 2-.1.6-.2 1.8-.7 2-1.4.3-.7.3-1.3.2-1.4-.1-.2-.3-.3-.6-.4Z" fill="currentColor"/></svg><span>WhatsApp</span><span aria-hidden="true">→</span></a></div></Container></section>}







